"""
Created by. Troniya
Created on Thu May 6 15:49:40 2021
"""

"""
** Module ID define **
"""
JETSON_ID = 0x10
CORTEX_ID = 0x20

"""
** CMD define **
"""
REQUEST_DEFAULT             = 0xA0
REQUEST_ODOMETER            = 0xA0
REQUEST_BOTTOM_SENSOR       = 0xA1
REQUEST_BASIC_MODULE        = 0xA2
REQUEST_FLAME_SENSOR        = 0xA3
REQUEST_ECO_MODULE          = 0xA4
REQUEST_PIR_SENSOR          = 0xA5
REQUEST_CO2_GAS_SENSOR      = 0xA6
REQUEST_DUST_SENSOR         = 0xA7
REQUEST_TEMPERATURE_SENSOR  = 0xA8
REQUEST_uWAVE_SENSOR        = 0xA9
REQUEST_SOUND_SENSOR        = 0xAA
REQUEST_BATTERY_SENSOR        = 0xAB

ANSWER_ODOMETER            = 0xB0
ANSWER_BOTTOM_SENSOR       = 0xB1
ANSWER_BASIC_MODULE        = 0xB2
ANSWER_FLAME_SENSOR        = 0xB3
ANSWER_ECO_MODULE          = 0xB4
ANSWER_PIR_SENSOR          = 0xB5
ANSWER_CO2_GAS_SENSOR      = 0xB6
ANSWER_DUST_SENSOR         = 0xB7
ANSWER_TEMPERATURE_SENSOR  = 0xB8
ANSWER_uWAVE_SENSOR        = 0xB9
ANSWER_SOUND_SENSOR        = 0xBA
ANSWER_BATTERY_SENSOR        = 0xBB

CONTROL_DRIVE   = 0xC0
CONTROL_MODULE  = 0xC1
CONTROL_ENCODER = 0xC2

"""
** MID define **
"""
MID_ENCODER_WHEEL_1 = 0x80
MID_ENCODER_WHEEL_2 = 0x81
MID_ENCODER_WHEEL_3 = 0x82

MID_BOTTOM_ULTRASONIC_SENSOR = 0x80
MID_BOTTOM_PSD_SENSOR = 0x81

MID_BASIC_SWITCH = 0x80

MID_FLAME_SENSOR = 0x80

MID_ECO_LUX_SENSOR      = 0x80
MID_ECO_ATTI_X          = 0x81
MID_ECO_ATTI_Y          = 0x82
MID_ECO_ATTI_Z          = 0x83
MID_ECO_PRESSURE        = 0x84
MID_ECO_GEOMAGNETISM    = 0x85

MID_PIR_SENSOR = 0x80

MID_CO2_GAS_SENSOR = 0x80

MID_DUST_SENSOR = 0x80

MID_TEMPERATURE_SENSOR = 0x80

MID_uWAVE_MOTION_SENSOR = 0x80

MID_SOUND_1_SENSOR = 0x80
MID_SOUND_2_SENSOR = 0x81
MID_SOUND_3_SENSOR = 0x82
MID_SOUND_4_SENSOR = 0x83

# Control Drive
MID_CONTROL_X_LINEAR_VELOCITY  = 0x80
MID_CONTROL_Y_LINEAR_VELOCITY  = 0x81
MID_CONTROL_W_ANGULAR_VELOCITY = 0x82

# Control Modules
MID_CONTROL_LED     = 0x80
MID_CONTROL_BUZZER  = 0x81

# Control Encoder
MID_CONTROL_CLEAR_ENC = 0x80

MID_BATTERY = 0x80
